version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0

cache_key: &cache_key aws-ccp-go-20230530-{{ checksum "go.sum" }}

executors:
  docker-go:
    docker:
        - image: cimg/go:1.21.0
commands:
  lint-test:
    steps:
      - checkout 
      - aws-cli/setup:
          role_session_name: circle-job
          role_arn: $AWS_IAM_ROLE
      - restore_cache:
          name: Restore dep cache
          keys: 
            - *cache_key 
      - run: 
         name: Install dependencies
         command: make setup
      - save_cache:
          name: Save dep cache 
          key: *cache_key
          paths: 
            - ~/go/pkg
            - bin/golangci-lint
      # - run:
      #     name: Run linter
      #     command: make lint
      - run:
          name: Run test
          command: go test ./...
  codegen: 
    steps:
      - run: 
          name: Run go generate
          command: go generate ./codegen/codegen.go
  build-code:
    steps: 
      - run: 
          name: Build code 
          command: make build

jobs:
  lint-build-test:
    executor: docker-go
    steps:
      - lint-test 
      - codegen
      - build-code
  release:
    executor: docker-go
    steps: 
      - lint-test 
      - build-code
      - run:
          name: tag & release
          command: echo "releasing this branch"

workflows:
  build-test-release:
    jobs:
     - lint-build-test:
         context: org-global 
     - release:
         context: org-global
         requires:
           - lint-build-test
         filters: 
           branches:
             only:
               - master
